# Generated by EXO — https://github.com/Harsh-BH/Exo
APP_NAME := myapp
BINARY   := bin/$(APP_NAME)
IMAGE    := $(APP_NAME):latest

.PHONY: all build test run clean docker-build docker-push deploy lint fmt

all: build

## Build the binary
build:
	@echo "→ Building $(BINARY)..."
	@mkdir -p bin
	go build -ldflags="-s -w" -o $(BINARY) .

## Run tests
test:
	@echo "→ Running tests..."
	go test ./... -v -race

## Run the application locally
run:
	@echo "→ Running $(APP_NAME)..."
	go run .

## Format code
fmt:
	gofmt -s -w .

## Lint code (requires golangci-lint)
lint:
	golangci-lint run ./...

## Build Docker image
docker-build:
	@echo "→ Building Docker image $(IMAGE)..."
	docker build -t $(IMAGE) .

## Push Docker image to registry
docker-push:
	@echo "→ Pushing $(IMAGE)..."
	docker push $(IMAGE)

## Deploy to Kubernetes
deploy:
	@echo "→ Deploying to Kubernetes..."
	kubectl apply -f k8s/

## Remove build artifacts
clean:
	@echo "→ Cleaning..."
	rm -rf bin/

## Show help
help:
	@grep -E '^##' Makefile | sed 's/## //'
