import CodeBlock from '@/components/CodeBlock';

export default function CLICleanPage() {
  return (
    <article>
      <div className="mb-8">
        <p className="text-arch-text-dim text-xs tracking-widest uppercase mb-1">── CLI REFERENCE ──</p>
        <h1 className="text-3xl font-bold text-arch-text-bright mb-3">exo clean</h1>
        <p className="text-arch-text-dim text-sm border-l-2 border-arch-cyan pl-4">
          Remove all files and directories generated by Exo from the current project.
        </p>
      </div>

      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-3"><span className="text-arch-green mr-2">##</span> Synopsis</h2>
        <CodeBlock language="bash" code={`exo clean [--yes]`} />
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-3"><span className="text-arch-green mr-2">##</span> Description</h2>
        <p className="text-sm text-arch-text mb-4">
          Reads <code className="text-arch-pink">.exo.yaml</code> and removes all infrastructure
          assets that Exo would have generated — Dockerfiles, Terraform directories, Kubernetes
          manifests, CI pipelines, Helm charts, monitoring configs, and project files.
        </p>
        <p className="text-sm text-arch-text mb-4">
          By default, prompts for confirmation before deleting anything. Pass{' '}
          <code className="text-arch-pink">--yes</code> to skip the prompt (useful in CI).
          The <code className="text-arch-pink">.exo.yaml</code> config file itself is{' '}
          <strong className="text-arch-text-bright">not</strong> removed.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-3"><span className="text-arch-green mr-2">##</span> Flags</h2>
        <table className="docs-table w-full text-xs">
          <thead><tr><th>Flag</th><th>Description</th></tr></thead>
          <tbody>
            <tr><td><code>--yes</code></td><td>Skip the confirmation prompt and delete immediately</td></tr>
          </tbody>
        </table>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-3"><span className="text-arch-green mr-2">##</span> What Gets Removed</h2>
        <table className="docs-table w-full text-xs">
          <thead><tr><th>Asset</th><th>Path</th></tr></thead>
          <tbody>
            <tr><td>Dockerfile</td><td><code>Dockerfile</code></td></tr>
            <tr><td>Docker Compose</td><td><code>docker-compose.*.yml</code></td></tr>
            <tr><td>Terraform</td><td><code>infra/&lt;provider&gt;/</code></td></tr>
            <tr><td>Kubernetes</td><td><code>k8s/</code></td></tr>
            <tr><td>Helm Chart</td><td><code>charts/&lt;name&gt;/</code></td></tr>
            <tr><td>CI/CD</td><td><code>.github/workflows/ci.yml</code>, <code>.gitlab-ci.yml</code></td></tr>
            <tr><td>Monitoring</td><td><code>monitoring/</code>, <code>grafana_dashboard.json</code>, <code>alerts.yml</code></td></tr>
            <tr><td>Project files</td><td><code>Makefile</code>, <code>.env.example</code>, <code>.gitignore</code></td></tr>
          </tbody>
        </table>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-3"><span className="text-arch-green mr-2">##</span> Examples</h2>
        <div className="space-y-4">
          <div>
            <p className="text-arch-text-bright text-sm font-semibold mb-2">Interactive (with confirmation)</p>
            <CodeBlock language="bash" code={`$ exo clean
The following will be deleted:
  Dockerfile, k8s/, infra/aws/, .github/workflows/ci.yml

Proceed? [y/N]: y
Cleaned 4 items.`} />
          </div>
          <div>
            <p className="text-arch-text-bright text-sm font-semibold mb-2">Non-interactive (CI/CD)</p>
            <CodeBlock language="bash" code={`exo clean --yes`} />
          </div>
          <div>
            <p className="text-arch-text-bright text-sm font-semibold mb-2">Clean and regenerate with new config</p>
            <CodeBlock language="bash" code={`# Switch from AWS to GCP
exo clean --yes
# Edit .exo.yaml: provider: gcp
exo init --non-interactive`} />
          </div>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-3"><span className="text-arch-green mr-2">##</span> Notes</h2>
        <div className="space-y-2 text-sm text-arch-text-dim">
          <div className="flex gap-2"><span className="text-arch-red">!</span><span><code className="text-arch-pink">.exo.yaml</code> is preserved — it is never deleted by clean</span></div>
          <div className="flex gap-2"><span className="text-arch-red">!</span><span>Your application source code is never touched</span></div>
          <div className="flex gap-2"><span className="text-arch-cyan">→</span><span>Use <code className="text-arch-pink">exo status</code> first to see exactly what exists before cleaning</span></div>
          <div className="flex gap-2"><span className="text-arch-cyan">→</span><span>Use <code className="text-arch-pink">exo diff</code> to preview new output before regenerating</span></div>
        </div>
      </section>
    </article>
  );
}
