import CodeBlock from '@/components/CodeBlock';

export default function ConfigurationPage() {
  return (
    <article>
      <div className="mb-8">
        <p className="text-arch-text-dim text-xs tracking-widest uppercase mb-1">── CORE CONCEPTS ──</p>
        <h1 className="text-3xl font-bold text-arch-text-bright mb-3">Configuration</h1>
        <p className="text-arch-text-dim text-sm border-l-2 border-arch-purple pl-4">
          Exo stores all project settings in a single <code className="text-arch-pink">.exo.yaml</code> file at the project root.
        </p>
      </div>

      {/* Format */}
      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-4">
          <span className="text-arch-green mr-2">##</span> File Format
        </h2>
        <p className="text-sm text-arch-text mb-4">
          The config file is auto-generated by <code className="text-arch-pink">exo init</code> and
          updated by <code className="text-arch-pink">exo add</code>. You can also edit it by hand.
        </p>
        <CodeBlock language="yaml" filename=".exo.yaml" showLineNumbers code={`name: my-service
language: go
provider: aws
ci: github-actions
monitoring: prometheus
database: postgres`} />
      </section>

      {/* Fields */}
      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-4">
          <span className="text-arch-green mr-2">##</span> Field Reference
        </h2>
        <table className="docs-table w-full text-xs">
          <thead>
            <tr><th>Field</th><th>Type</th><th>Options</th><th>Description</th></tr>
          </thead>
          <tbody>
            <tr>
              <td><code>name</code></td>
              <td>string</td>
              <td>any</td>
              <td>Project name used in generated manifests, Helm charts, and CI configs</td>
            </tr>
            <tr>
              <td><code>language</code></td>
              <td>string</td>
              <td><code>go</code>, <code>node</code>, <code>python</code></td>
              <td>Primary language — determines Dockerfile base image and build commands</td>
            </tr>
            <tr>
              <td><code>provider</code></td>
              <td>string</td>
              <td><code>aws</code>, <code>gcp</code>, <code>azure</code>, <code>none</code></td>
              <td>Cloud provider for Terraform infrastructure modules</td>
            </tr>
            <tr>
              <td><code>ci</code></td>
              <td>string</td>
              <td><code>github-actions</code>, <code>gitlab-ci</code>, <code>none</code></td>
              <td>CI/CD platform — generates pipeline configuration</td>
            </tr>
            <tr>
              <td><code>monitoring</code></td>
              <td>string</td>
              <td><code>prometheus</code>, <code>none</code></td>
              <td>Monitoring stack — Prometheus + Grafana docker-compose</td>
            </tr>
            <tr>
              <td><code>database</code></td>
              <td>string</td>
              <td><code>postgres</code>, <code>mysql</code>, <code>mongo</code>, <code>redis</code>, <code>none</code></td>
              <td>Database — generates docker-compose service</td>
            </tr>
          </tbody>
        </table>
      </section>

      {/* How it's used */}
      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-4">
          <span className="text-arch-green mr-2">##</span> How Config is Used
        </h2>
        <div className="space-y-4 text-sm text-arch-text">
          <div className="flex gap-3 items-start">
            <span className="text-arch-cyan font-bold mt-0.5">1.</span>
            <div>
              <p className="text-arch-text-bright font-semibold">Template Rendering</p>
              <p className="text-arch-text-dim text-xs">
                Every template receives the full config as <code className="text-arch-pink">{`{{ .Name }}`}</code>,{' '}
                <code className="text-arch-pink">{`{{ .Language }}`}</code>, etc.
              </p>
            </div>
          </div>
          <div className="flex gap-3 items-start">
            <span className="text-arch-cyan font-bold mt-0.5">2.</span>
            <div>
              <p className="text-arch-text-bright font-semibold">Status & Validation</p>
              <p className="text-arch-text-dim text-xs">
                <code className="text-arch-pink">exo status</code> and{' '}
                <code className="text-arch-pink">exo validate</code> read the config to know what should exist.
              </p>
            </div>
          </div>
          <div className="flex gap-3 items-start">
            <span className="text-arch-cyan font-bold mt-0.5">3.</span>
            <div>
              <p className="text-arch-text-bright font-semibold">Add Command</p>
              <p className="text-arch-text-dim text-xs">
                <code className="text-arch-pink">exo add</code> updates the config YAML then regenerates affected templates.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Go struct */}
      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-4">
          <span className="text-arch-green mr-2">##</span> Internal Go Struct
        </h2>
        <CodeBlock language="go" filename="internal/config/config.go" showLineNumbers code={`type ExoConfig struct {
    Name       string \`yaml:"name"\`
    Language   string \`yaml:"language"\`
    Provider   string \`yaml:"provider"\`
    CI         string \`yaml:"ci"\`
    Monitoring string \`yaml:"monitoring"\`
    Database   string \`yaml:"database"\`
}

// LoadConfig reads .exo.yaml from the current directory.
func LoadConfig() (*ExoConfig, error) {
    data, err := os.ReadFile(".exo.yaml")
    if err != nil {
        return nil, fmt.Errorf("no .exo.yaml found — run 'exo init' first")
    }
    var cfg ExoConfig
    if err := yaml.Unmarshal(data, &cfg); err != nil {
        return nil, fmt.Errorf("invalid .exo.yaml: %w", err)
    }
    return &cfg, nil
}

// SaveConfig writes the config back to .exo.yaml.
func SaveConfig(cfg *ExoConfig) error {
    data, err := yaml.Marshal(cfg)
    if err != nil {
        return err
    }
    return os.WriteFile(".exo.yaml", data, 0644)
}`} />
      </section>

      {/* Examples */}
      <section className="mb-10">
        <h2 className="text-xl font-bold text-arch-text-bright mb-4">
          <span className="text-arch-green mr-2">##</span> Examples
        </h2>
        <div className="space-y-4">
          <div>
            <p className="text-arch-text-bright text-sm font-semibold mb-2">Node.js + GCP + GitLab</p>
            <CodeBlock language="yaml" code={`name: api-gateway
language: node
provider: gcp
ci: gitlab-ci
monitoring: prometheus
database: mongo`} />
          </div>
          <div>
            <p className="text-arch-text-bright text-sm font-semibold mb-2">Python + No Cloud (Local Dev Only)</p>
            <CodeBlock language="yaml" code={`name: ml-pipeline
language: python
provider: none
ci: none
monitoring: none
database: redis`} />
          </div>
          <div>
            <p className="text-arch-text-bright text-sm font-semibold mb-2">Go + Azure Full Stack</p>
            <CodeBlock language="yaml" code={`name: payment-service
language: go
provider: azure
ci: github-actions
monitoring: prometheus
database: postgres`} />
          </div>
        </div>
      </section>
    </article>
  );
}
