package exo

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// knownGeneratedFiles lists file/dir patterns that "exo gen" can produce.
// Relative to the project root.
var knownGeneratedFiles = []string{
	"Dockerfile",
	"docker-compose.yml",
	"docker-compose.postgres.yml",
	"docker-compose.mongo.yml",
	"docker-compose.mysql.yml",
	"docker-compose.redis.yml",
	".env.example",
	".gitignore",
	"Makefile",
	"alerts.yml",
	"grafana_dashboard.json",
	"sonar-project.properties",
	"renovate.json",
	"LICENSE",
	"README.md",
	".pre-commit-config.yaml",
	// directories
	"k8s/",
	"charts/",
	"infra/",
	"monitoring/",
	".devcontainer/",
	".github/dependabot.yml",
	".github/workflows/",
}

var cleanCmd = &cobra.Command{
	Use:   "clean",
	Short: "Remove files previously generated by exo gen",
	Long: `Remove files and directories that were generated by 'exo gen'.

By default runs in interactive mode — each file/directory is listed and you
are prompted before deletion.  Use --yes to skip confirmation.

Use --dry-run to preview what would be removed without actually deleting anything.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cwd, err := os.Getwd()
		if err != nil {
			return err
		}

		dryRun, _ := cmd.Flags().GetBool("dry-run")
		yes, _ := cmd.Flags().GetBool("yes")

		if dryRun {
			fmt.Println("  [dry-run mode — no files will be deleted]")
		}

		found := collectExisting(cwd, knownGeneratedFiles)
		if len(found) == 0 {
			fmt.Println("Nothing to clean — no generated files found.")
			return nil
		}

		fmt.Printf("Found %d generated file(s)/dir(s):\n\n", len(found))
		for _, f := range found {
			rel, _ := filepath.Rel(cwd, f)
			fmt.Printf("  %s\n", rel)
		}
		fmt.Println()

		if !dryRun {
			if !yes && !confirmPrompt("Remove all of the above?") {
				fmt.Println("Aborted.")
				return nil
			}
			removed := 0
			for _, f := range found {
				rel, _ := filepath.Rel(cwd, f)
				if err := os.RemoveAll(f); err != nil {
					fmt.Fprintf(os.Stderr, "  ✗  could not remove %s: %v\n", rel, err)
				} else {
					fmt.Printf("  ✓  removed %s\n", rel)
					removed++
				}
			}
			fmt.Printf("\nDone — removed %d item(s).\n", removed)
		}
		return nil
	},
}

// collectExisting returns absolute paths for all known generated files/dirs
// that actually exist under root.
func collectExisting(root string, patterns []string) []string {
	var found []string
	for _, pattern := range patterns {
		abs := filepath.Join(root, filepath.FromSlash(pattern))
		if _, err := os.Stat(abs); err == nil {
			found = append(found, abs)
		}
	}
	return found
}

// confirmPrompt asks the user y/n and returns true for y/Y/yes.
func confirmPrompt(question string) bool {
	fmt.Printf("%s [y/N]: ", question)
	scanner := bufio.NewScanner(os.Stdin)
	scanner.Scan()
	answer := strings.TrimSpace(strings.ToLower(scanner.Text()))
	return answer == "y" || answer == "yes"
}

func init() {
	rootCmd.AddCommand(cleanCmd)
	cleanCmd.Flags().Bool("dry-run", false, "Preview what would be removed without deleting")
	cleanCmd.Flags().BoolP("yes", "y", false, "Skip confirmation prompt")
}
