package exo

import (
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/Harsh-BH/Exo/internal/config"
	"github.com/Harsh-BH/Exo/internal/renderer"
)

// ─── README ──────────────────────────────────────────────────────────────────

const readmeTmpl = `# {{.AppName}}

> Generated by [exo](https://github.com/Harsh-BH/Exo)

## Overview

A **{{.Language}}** service{{if .Framework}} built with **{{.Framework}}**{{end}}.

## Getting Started

` + "```" + `bash
# Install dependencies
{{- if eq .Language "go"}}
go mod download
{{- else if eq .Language "node"}}
npm install
{{- else if eq .Language "python"}}
pip install -r requirements.txt
{{- end}}

# Run the application
{{- if eq .Language "go"}}
go run .
{{- else if eq .Language "node"}}
npm start
{{- else if eq .Language "python"}}
python main.py
{{- end}}
` + "```" + `

{{if .DB}}## Database

This project uses **{{.DB}}**. A compose file can be generated with:

` + "```" + `bash
exo gen db --db {{.DB}}
` + "```" + `
{{end}}

## Docker

` + "```" + `bash
docker build -t {{.AppName}} .
docker run -p {{.Port}}:{{.Port}} {{.AppName}}
` + "```" + `

## License

MIT
`

func generateReadme(cwd string, data config.TemplateData, dryRun, force bool) error {
	out := filepath.Join(cwd, "README.md")
	if err := renderer.RenderTemplateString(readmeTmpl, out, data, dryRun, force); err != nil {
		return fmt.Errorf("readme: %w", err)
	}
	if !dryRun {
		fmt.Println("  ✓  README → README.md")
	}
	return nil
}

// ─── PRE-COMMIT ───────────────────────────────────────────────────────────────

const preCommitTmpl = `# .pre-commit-config.yaml — generated by exo
repos:
{{- if eq .Language "go"}}
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-unit-tests
{{- else if eq .Language "node"}}
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts|jsx|tsx)$
{{- else if eq .Language "python"}}
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
{{- end}}
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
`

func generatePreCommit(cwd string, data config.TemplateData, dryRun, force bool) error {
	out := filepath.Join(cwd, ".pre-commit-config.yaml")
	if err := renderer.RenderTemplateString(preCommitTmpl, out, data, dryRun, force); err != nil {
		return fmt.Errorf("pre-commit: %w", err)
	}
	if !dryRun {
		fmt.Println("  ✓  pre-commit config → .pre-commit-config.yaml")
	}
	return nil
}

// ─── DEVCONTAINER ─────────────────────────────────────────────────────────────

const devcontainerTmpl = `{
  "name": "{{.AppName}}",
{{- if eq .Language "go"}}
  "image": "mcr.microsoft.com/devcontainers/go:1.22",
{{- else if eq .Language "node"}}
  "image": "mcr.microsoft.com/devcontainers/javascript-node:20",
{{- else if eq .Language "python"}}
  "image": "mcr.microsoft.com/devcontainers/python:3.12",
{{- else}}
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
{{- end}}
  "features": {
    "ghcr.io/devcontainers/features/docker-in-docker:2": {},
    "ghcr.io/devcontainers/features/git:1": {}
  },
  "forwardPorts": [{{.Port}}],
  "postCreateCommand": "{{- if eq .Language "go"}}go mod download{{- else if eq .Language "node"}}npm install{{- else if eq .Language "python"}}pip install -r requirements.txt{{- else}}echo ready{{- end}}",
  "customizations": {
    "vscode": {
      "extensions": [
{{- if eq .Language "go"}}
        "golang.go"
{{- else if eq .Language "node"}}
        "esbenp.prettier-vscode",
        "dbaeumer.vscode-eslint"
{{- else if eq .Language "python"}}
        "ms-python.python",
        "ms-python.black-formatter"
{{- end}}
      ]
    }
  }
}
`

func generateDevcontainer(cwd string, data config.TemplateData, dryRun, force bool) error {
	dir := filepath.Join(cwd, ".devcontainer")
	out := filepath.Join(dir, "devcontainer.json")
	if err := renderer.RenderTemplateString(devcontainerTmpl, out, data, dryRun, force); err != nil {
		return fmt.Errorf("devcontainer: %w", err)
	}
	if !dryRun {
		fmt.Println("  ✓  Dev container → .devcontainer/devcontainer.json")
	}
	return nil
}

// ─── RENOVATE ─────────────────────────────────────────────────────────────────

const renovateTmpl = `{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["config:recommended"],
  "labels": ["dependencies"],
  "automerge": false,
  "platformAutomerge": false,
  "schedule": ["before 6am on Monday"],
  "packageRules": [
    {
      "matchUpdateTypes": ["patch"],
      "automerge": true
    }
  ]
}
`

func generateRenovate(cwd string, data config.TemplateData, dryRun, force bool) error {
	out := filepath.Join(cwd, "renovate.json")
	if err := renderer.RenderTemplateString(renovateTmpl, out, data, dryRun, force); err != nil {
		return fmt.Errorf("renovate: %w", err)
	}
	if !dryRun {
		fmt.Println("  ✓  Renovate config → renovate.json")
	}
	return nil
}

// ─── LICENSE ──────────────────────────────────────────────────────────────────

const mitLicense = `MIT License

Copyright (c) {{.Year}} {{.AppName}}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`

const apache2License = `Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/

Copyright (c) {{.Year}} {{.AppName}}

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
`

const gpl3License = `GNU GENERAL PUBLIC LICENSE
Version 3, 29 June 2007

Copyright (C) {{.Year}} {{.AppName}}

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
`

type licenseData struct {
	AppName string
	Year    int
}

func generateLicense(cwd string, data config.TemplateData, licenseType string, dryRun, force bool) error {
	ld := licenseData{AppName: data.AppName, Year: time.Now().Year()}

	var tmpl string
	switch strings.ToLower(licenseType) {
	case "apache2", "apache":
		tmpl = apache2License
	case "gpl3", "gpl":
		tmpl = gpl3License
	default:
		tmpl = mitLicense
		licenseType = "mit"
	}

	out := filepath.Join(cwd, "LICENSE")
	if err := renderer.RenderTemplateString(tmpl, out, ld, dryRun, force); err != nil {
		return fmt.Errorf("license: %w", err)
	}
	if !dryRun {
		fmt.Printf("  ✓  LICENSE (%s) → LICENSE\n", strings.ToUpper(licenseType))
	}
	return nil
}

// ─── DEPENDABOT ───────────────────────────────────────────────────────────────

const dependabotTmpl = `# .github/dependabot.yml — generated by exo
version: 2
updates:
{{- if eq .Language "go"}}
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
{{- else if eq .Language "node"}}
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
{{- else if eq .Language "python"}}
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
{{- end}}
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
`

func generateDependabot(cwd string, data config.TemplateData, dryRun, force bool) error {
	dir := filepath.Join(cwd, ".github")
	out := filepath.Join(dir, "dependabot.yml")
	if err := renderer.RenderTemplateString(dependabotTmpl, out, data, dryRun, force); err != nil {
		return fmt.Errorf("dependabot: %w", err)
	}
	if !dryRun {
		fmt.Println("  ✓  Dependabot config → .github/dependabot.yml")
	}
	return nil
}

// ─── SONARQUBE ────────────────────────────────────────────────────────────────

const sonarTmpl = `# sonar-project.properties — generated by exo
sonar.projectKey={{.AppName}}
sonar.projectName={{.AppName}}
sonar.projectVersion=1.0

{{- if eq .Language "go"}}
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
{{- else if eq .Language "node"}}
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
{{- else if eq .Language "python"}}
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/test_*.py,**/*_test.py
sonar.python.coverage.reportPaths=coverage.xml
{{- else}}
sonar.sources=.
{{- end}}
`

func generateSonarqube(cwd string, data config.TemplateData, dryRun, force bool) error {
	out := filepath.Join(cwd, "sonar-project.properties")
	if err := renderer.RenderTemplateString(sonarTmpl, out, data, dryRun, force); err != nil {
		return fmt.Errorf("sonarqube: %w", err)
	}
	if !dryRun {
		fmt.Println("  ✓  SonarQube config → sonar-project.properties")
	}
	return nil
}

// ─── SBOM (Software Bill of Materials) ───────────────────────────────────────

// sbomTmpl is a minimal CycloneDX 1.4 JSON skeleton used as a fallback when
// syft is not installed.  Projects should prefer running syft directly for a
// fully populated SBOM.
const sbomTmpl = `{
  "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:{{.AppName}}-sbom",
  "version": 1,
  "metadata": {
    "timestamp": "{{timestamp}}",
    "component": {
      "type": "application",
      "name": "{{.AppName}}",
      "version": "0.0.0",
      "language": "{{.Language}}"
    },
    "tools": [
      { "vendor": "Harsh-BH", "name": "exo", "version": "dev" }
    ]
  },
  "components": []
}
`

// generateSBOM tries to use syft for a full SBOM. If syft is not found it
// falls back to writing the minimal CycloneDX skeleton above.
func generateSBOM(cwd string, data config.TemplateData, dryRun, force bool) error {
	out := filepath.Join(cwd, "sbom.cdx.json")

	if dryRun {
		fmt.Printf("  [dry-run] would write → %s\n", out)
		return nil
	}

	// If syft is available, use it for a real SBOM
	if _, err := exec.LookPath("syft"); err == nil {
		stop := startSpinner("Generating SBOM with syft → sbom.cdx.json")
		syftErr := exec.Command("syft", ".", "-o", "cyclonedx-json="+out).Run()
		stop(syftErr)
		if syftErr != nil {
			return fmt.Errorf("syft: %w", syftErr)
		}
		return nil
	}

	// Fallback: write minimal CycloneDX skeleton
	fmt.Println("  ℹ  syft not found — writing minimal CycloneDX skeleton.")
	fmt.Println("     Install syft for a full SBOM: https://github.com/anchore/syft")

	// Replace {{timestamp}} manually since Go templates don't call functions inline
	tmpl := strings.ReplaceAll(sbomTmpl, "{{timestamp}}", time.Now().UTC().Format(time.RFC3339))
	if err := renderer.RenderTemplateString(tmpl, out, data, false, force); err != nil {
		return fmt.Errorf("sbom: %w", err)
	}
	fmt.Println("  ✓  SBOM (CycloneDX skeleton) → sbom.cdx.json")
	return nil
}
