package exo

import (
	"fmt"
	"path/filepath"

	"github.com/Harsh-BH/Exo/internal/config"
	"github.com/Harsh-BH/Exo/internal/renderer"
)

func generateDockerfile(cwd string, data config.TemplateData, dryRun, force bool) error {
	tmplMap := map[string]string{
		"node":   "node.tmpl",
		"python": "python.tmpl",
	}
	tmplFile, ok := tmplMap[data.Language]
	if !ok {
		tmplFile = "dockerfile.tmpl" // default → Go
	}

	tmplPath := filepath.Join("templates", "docker", tmplFile)
	outPath := filepath.Join(cwd, "Dockerfile")

	if err := renderFile(tmplPath, outPath, data, dryRun, force); err != nil {
		return fmt.Errorf("dockerfile: %w", err)
	}
	if !dryRun {
		fmt.Printf("  ✓  Dockerfile (%s) → Dockerfile\n", data.Language)
	}
	return nil
}

func generateDockerCompose(cwd string, data config.TemplateData, dryRun, force bool) error {
	tmplPath := filepath.Join("templates", "docker", "docker-compose.tmpl")
	outPath := filepath.Join(cwd, "docker-compose.yml")

	if err := renderFile(tmplPath, outPath, data, dryRun, force); err != nil {
		// Fallback: generate inline if template doesn't exist yet
		if err2 := renderer.RenderTemplateString(dockerComposeTmpl, outPath, data, dryRun, force); err2 != nil {
			return fmt.Errorf("docker-compose: %w", err2)
		}
	}
	if !dryRun {
		fmt.Printf("  ✓  docker-compose.yml → docker-compose.yml\n")
	}
	return nil
}

// dockerComposeTmpl is an inline fallback used until docker-compose.tmpl is on disk.
const dockerComposeTmpl = `# Generated by EXO — docker-compose.yml for {{.AppName}}
version: '3.9'

services:
  app:
    build: .
    container_name: {{.AppName}}
    ports:
      - "{{.Port}}:{{.Port}}"
    environment:
      - APP_ENV=development
{{- if eq .DB "postgres"}}
      - DATABASE_URL=postgres://admin:secret@postgres:5432/{{.AppName}}
    depends_on:
      - postgres
{{- else if eq .DB "mysql"}}
      - DATABASE_URL=mysql://admin:secret@mysql:3306/{{.AppName}}
    depends_on:
      - mysql
{{- else if eq .DB "mongo"}}
      - MONGO_URI=mongodb://admin:secret@mongo:27017/{{.AppName}}
    depends_on:
      - mongo
{{- else if eq .DB "redis"}}
      - REDIS_URL=redis://:secret@redis:6379/0
    depends_on:
      - redis
{{- end}}
    restart: unless-stopped

{{- if eq .DB "postgres"}}

  postgres:
    image: postgres:16-alpine
    container_name: {{.AppName}}-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: {{.AppName}}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
{{- else if eq .DB "mysql"}}

  mysql:
    image: mysql:8
    container_name: {{.AppName}}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: {{.AppName}}
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
{{- else if eq .DB "mongo"}}

  mongo:
    image: mongo:7
    container_name: {{.AppName}}-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: {{.AppName}}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
{{- else if eq .DB "redis"}}

  redis:
    image: redis:7-alpine
    container_name: {{.AppName}}-redis
    command: redis-server --requirepass secret
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
{{- end}}
{{- if eq .Monitoring "prometheus"}}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
{{- end}}

volumes:
{{- if eq .DB "postgres"}}
  postgres_data:
{{- else if eq .DB "mysql"}}
  mysql_data:
{{- else if eq .DB "mongo"}}
  mongo_data:
{{- else if eq .DB "redis"}}
  redis_data:
{{- end}}
`
